name: Deploy Vite App to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch: # This allows manual triggering

permissions:
  contents: read # Allow read access to the repository's contents
  pages: write # Allow write access to GitHub Pages for deployment
  id-token: write # Required for certain authentication (OIDC-based tokens)

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build with environment variables
      - name: Build the project
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }} # Add your secrets here
          VITE_DOCUMENT_KEY: ${{ secrets.VITE_DOCUMENT_KEY }}
          VITE_SHEET_OVERVIEW: ${{ secrets.VITE_SHEET_OVERVIEW }}
        run: npm run build

      # Step 5: Create .nojekyll file in dist folder to bypass Jekyll processing
      - name: Create .nojekyll file
        run: echo > dist/.nojekyll

      # Step 6: Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      # Step 7: Upload the dist folder as an artifact for deployment
      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist" # Ensure this path is correct

      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
